project:
  type: book
  output-dir: docs


book:
  title: "Ökosüsteemide toiminine"
  author: "Siim-Kaarel Sepp"
  date: today
  date-format: "MM YYYY"
  output-file: okosysteemide_toiminine
  chapters:
    - index.qmd
    - Koosluste_struktuur.qmd
    - koosluse_kirjeldamine.qmd
    - koosluse_energeetiline_struktuur.qmd
    # - Okosysteemide_klassifitseerimine.qmd
    # - references.qmd

# bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrbook
