project:
  type: book
  output-dir: docs


book:
  title: "Ökosüsteemide toiminine"
  author: "Siim-Kaarel Sepp"
  date: today
  date-format: "MM YYYY"
  output-file: okosysteemide_toiminine
  chapters:
    - index.qmd
    - Koosluste_struktuur.qmd
    - koosluse_kirjeldamine.qmd
    - koosluse_energeetiline_struktuur.qmd
    - Koosluse_stabiilsus.qmd
    # - Okosysteemide_klassifitseerimine.qmd # TODO: See tuleb 2026. aastaks läbi mõelda!
    # - references.qmd

# bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: false
  pdf:
    number-sections: false
    documentclass: book
    geometry:
      - top=20mm
      - left=20mm
      - right=20mm
      - bottom=20mm
