project:
  type: website
  output-dir: docs

website:
  title: "okosysteemide-toimimine"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Koosluste_struktuur.qmd
        text: Koosluste struktuur
      - href: Okosysteemide_klassifitseerimine.qmd
        text: Ökosüsteemide klassifitseerimine

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

